Update

diff --git a/localbin/.local/bin/autostart b/localbin/.local/bin/autostart
--- a/localbin/.local/bin/autostart
+++ b/localbin/.local/bin/autostart
@@ -12,7 +12,7 @@
 #Created:
 #   Mon 22 November 2021, 03:15:54 PM [GMT+1]
 #Modified:
-#   Mon 14 August 2023, 05:30:34 PM [GMT+1]
+#   Thu 17 August 2023, 05:52:27 PM [GMT+1]
 #
 #Description:
 #   <Todo>
@@ -21,9 +21,9 @@
 #   <None>
 #
 
-if command -v /usr/libexec/polkit-gnome-authentication-agent-1 &>/dev/null; then
-  if ! pgrep -f "/usr/libexec/polkit-gnome-authentication-agent-1" >/dev/null; then
-    /usr/libexec/polkit-gnome-authentication-agent-1 &
+if command -v /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &>/dev/null; then
+  if ! pgrep -f "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1" >/dev/null; then
+    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
   else
     echo "polkit-gnome already Running"
   fi
@@ -160,17 +160,17 @@ else
   echo "touchpad-indicator could not be found"
 fi
 
-if command -v battray &>/dev/null; then
-  if ! pgrep -x "battray" >/dev/null; then
+if command -v cbatticon &>/dev/null; then
+  if ! pgrep -x "cbatticon" >/dev/null; then
     (
       sleep 2s
-      battray
+      cbatticon
     ) &
   else
-    echo "battray already Running"
+    echo "cbatticon already Running"
   fi
 else
-  echo "battray could not be found"
+  echo "cbatticon could not be found"
 fi
 
 if command -v pasystray &>/dev/null; then
