Update

diff --git a/localbin/.local/bin/autostart b/localbin/.local/bin/autostart
--- a/localbin/.local/bin/autostart
+++ b/localbin/.local/bin/autostart
@@ -12,7 +12,7 @@
 #Created:
 #   Mon 22 November 2021, 03:15:54 PM [GMT+1]
 #Modified:
-#   Sun 06 August 2023, 10:49:04 AM [GMT+1]
+#   Sun 06 August 2023, 06:58:02 PM [GMT+1]
 #
 #Description:
 #   <Todo>
@@ -172,17 +172,17 @@ else
     echo "cbatticon could not be found"
 fi
 
-if command -v volumeicon &>/dev/null; then
-    if ! pgrep -x "volumeicon" >/dev/null; then
+if command -v pasystray &>/dev/null; then
+    if ! pgrep -x "pasystray" >/dev/null; then
         (
             sleep 5s
-            volumeicon
+            pasystray
         ) &
     else
-        echo "volumeicon already Running"
+        echo "pasystray already Running"
     fi
 else
-    echo "volumeicon could not be found"
+    echo "pasystray could not be found"
 fi
 
 if command -v gufwicon &>/dev/null; then
