Update Kiss Package Manager
Signed-off-by: The-Repo-Club <wayne6324@gmail.com>

diff --git a/localbin/.local/bin/kiss/kiss-outdated b/localbin/.local/bin/kiss/kiss-outdated
--- a/localbin/.local/bin/kiss/kiss-outdated
+++ b/localbin/.local/bin/kiss/kiss-outdated
@@ -1,13 +1,15 @@
-#!/bin/sh
+#!/bin/sh -ef
 # Check repository for outdated packages
 
-die() {
-    printf '%s\n' "$*" >&2
-    exit 1
-}
+repology_version() {
+    # Grab the package's version as known by repology.org by downloading the
+    # svg latest-version badge and extracting the version from the xml.
+    repology_name "$1"
 
-mkcd() {
-    mkdir -p "$1" && cd "$1"
+    r=$(curl -Ss "https://repology.org/badge/latest-versions/$remote.svg") && {
+        remote_ver=${r%</text>*}
+        remote_ver=${remote_ver##*>}
+    }
 }
 
 repology_name() {
@@ -17,10 +19,11 @@ repology_name() {
         remote=${1%%-bin}
         remote=${remote%%-git}
 
+        printf %s "$remote" |
+
         # Remote names are all lowercase.
-        tr '[:upper:]' '[:lower:]' <<EOF |
-$remote
-EOF
+        tr '[:upper:]' '[:lower:]' |
+
         # Remote always uses -.
         tr _ -
     )
@@ -66,10 +69,6 @@ EOF
 
         font-awesome-ttf)
             remote=fonts:fontawesome
-        ;;
-
-        foot-pgo)
-            remote=foot
         ;;
 
         gc)
@@ -127,10 +126,6 @@ EOF
         libmupdf | libxaw3d)
             # TODO [community]: Rename packages?
             remote=${remote##lib}
-        ;;
-
-        libseat)
-            remote=seatd
         ;;
 
         links2)
@@ -207,10 +202,6 @@ EOF
             remote=st-term
         ;;
 
-        sway-no-seat | sway-tiny)
-            remote=sway
-        ;;
-
         terminus-font)
             remote=fonts:terminus
         ;;
@@ -239,70 +230,60 @@ EOF
     esac
 }
 
-repology_version() {
-    [ -f "$1.svg" ] || return 1
-    read -r remote_ver < "$1.svg" || :
-    remote_ver=${remote_ver%</text>*}
-    remote_ver=${remote_ver##*>}
-}
-
-repo_version() {
-    read -r ver _ 2>/dev/null < "$2/version" || {
-        printf '%-30s local version not found\n' "$1" >&2
-        return 1
-    }
-
-    [ "$ver" != git ]
-}
-
-get_outdated() {
-    repo=${repo%%/}
-    printf '\n[Checking Repology for outdated packages in %s]\n\n' "$repo" >&2
+main() {
+    printf '\n[Checking Repology for outdated packages in %s]\n\n' "${1%%/}" >&2
 
     for pkg in */; do
         pkg=${pkg%%/}
-        repology_name "${pkg##*/}"
 
-        [ "$remote" = - ] ||
-            set -- "$@" -z "$remote.svg" \
-                "https://repology.org/badge/latest-versions/$remote.svg"
-    done
-
-    mkcd "$tmp/${repo##*/}"
-
-    curl -SsZ --parallel-max 16 --remote-name-all "$@" ||
-        die 'fatal: network error'
-
-    for _pkg in "$OLDPWD"/*/; do
-        pkg=${_pkg%%/}
-        pkg=${pkg##*/}
-
-        repo_version  "$pkg" "$_pkg" || continue
-        repology_name "$pkg"
-        repology_version "$remote" || continue
-
-        case $remote_ver in *", $ver"* | *"$ver,"* | "$ver" | - | '')
+        read -r ver _ 2>/dev/null < "$pkg/version" || {
+            printf '%-30s local version not found\n' "$pkg" >&2
             continue
+        }
+
+        [ "$ver" = git ] &&
+            continue
+
+        repology_version "$pkg" || {
+            printf '%-30s network error\n' "$pkg" >&2
+            continue
+        }
+
+        case $remote_ver in
+            *", $ver"* | *"$ver,"* | "$ver")
+                # Package up-to-date, do nothing.
+            ;;
+
+            '' | ' ')
+                printf '\n%s: empty response\n' "$pkg" >&2
+                printf 'possible causes:\n' >&2
+                printf '    package name differs from repology name,\n' >&2
+                printf '    package not tracked by repology,\n' >&2
+                printf '    network error\n\n' >&2
+            ;;
+
+            '-')
+                # No version scheme, do nothing.
+            ;;
+
+            *)
+                printf '%-30s %s -> %s\n' "$pkg" "$ver" "$remote_ver"
+            ;;
         esac
-
-        printf '%-30s %s -> %s\n' "$pkg" "$ver" "$remote_ver"
     done
 }
 
-main() {
-    set -e
+for repo do
+    [ "$repo" ] || {
+        printf 'usage: kiss outdated /path/to/repo\n' >&2
+        exit 1
+    }
 
-    [ "$1" ] ||
-        die 'usage: kiss [ou]tdated /path/to/repo...'
+    cd "$repo" 2>/dev/null || {
+        printf 'repository %s is inaccessible\n' "$repo" >&2
+        exit 1
+    }
 
-    mkdir -p "${tmp:=${XDG_CACHE_HOME:-"$HOME/.cache"}/kiss/repology}"
-
-    for repo do
-        old_pwd=$PWD
-        cd "$repo"
-        get_outdated
-        cd "$old_pwd"
-    done
-}
-
-main "$@"
+    main "$repo"
+    cd "$OLDPWD" || exit 1
+done
